routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');
Route::post('comment', 'HomeController@storeComment')->name('comment');
Route::post('contacts', 'HomeController@storeContact')->name('contact');
Route::post('newsletter', 'HomeController@storeNewsLetter')->name('newsletter');
Route::get('sitemap', 'HomeController@sitemap')->name('sitemap');
Route::get('sitemap.xml', 'HomeController@sitemap')->name('sitemap');

Auth::routes();
Route::get('/backup', 'HomeController@backup')->middleware('auth'); 
Route::get('/refresh', 'HomeController@refresh')->middleware('auth');
Route::group(['middleware' => ['auth', 'permission'], 'prefix' => 'backend', 'namespace' => 'Backend'], function() {

	Route::get('/', 'DashboardController@index')->name('backend.dashboard');
	Route::resource('category', 'CategoryController');
	Route::resource('page', 'PageController');
	Route::resource('post', 'PostController');
	Route::resource('gallery', 'GalleryController');
	Route::resource('user', 'UserController');
	Route::resource('role', 'RoleController');
	Route::resource('faq', 'FaqController');
	Route::resource('partner', 'PartnerController');
	Route::resource('testimonial', 'TestimonialController');
  Route::resource('job', 'JobController');
  Route::resource('worker', 'WorkerController');
  Route::resource('order', 'OrderController');
	Route::get('contact', 'DashboardController@allContact')->name('contact.index');
	Route::get('contact/{id}', 'DashboardController@getContact')->name('contact.show');
	Route::get('comment', 'DashboardController@allComment')->name('comment.index');
	Route::get('comment/{id}', 'DashboardController@getComment')->name('comment.show');
	Route::get('setting', 'SettingController@index')->name('setting.index');
	Route::post('setting', 'SettingController@store')->name('setting.store');
});
/*Front Route*/
Route::get('/{slug}', 'RouteController@index')->name('url');

app/Models/Worker.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Worker extends Model
{
    protected $fillable= [
      'hour_rate', 'working_hour_per_day', 'working_day_per_month', 'availability', 'user_id', 'status', 'slug', 'rate_type'
    ];

    public function user(){

        return $this->belongsTo('App\Models\User','user_id');
    }

    public function orders(){
        return $this->hasMany('App\Models\Order');
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Http\Controllers\SeoController;

class CategoryController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(Category $category)
    {
        $this->middleware('auth');
        $this->category = $category;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->category->latest()->get();
        return view('backend.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('backend.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, ['title' => 'required|unique:seos', 'file' => 'image|mimes:jpg,png,jpeg,gif|max:2048','description' => 'max:240']);

        $request['slug'] = str_slug($request->title);

        if ($request->has('file')) {

            $image = $request->file('file');
            $ext =  $image->getClientOriginalExtension();
            $file_path ='/categories';
            $name = $request->slug.'.'.$ext;
            $path = $image->storeAs($file_path, $name, 'upload');
            $request['image'] = $path;
        }

        $category = $this->category->create($request->all());
        $seo = SeoController::create('category', $category);

        return redirect()->route('category.index')->with('success', 'Category created successfully');
        

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
       return redirect($category->slug);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->category->find($id);
        return view('backend.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = $this->category->find($id);
        $this->validate($request, ['title' => 'required|unique:categories,title,'.$category->id, 'file' => 'image|mimes:jpg,png,jpeg,gif|max:2048','description' => 'max:240']);

        $request['slug'] = str_slug($request->title);
        if ($request->has('file')) {
            $image = $request->file('file');
            $ext =  $image->getClientOriginalExtension();
            $file_path ='/categories';
            $name = $request->slug.'.'.$ext;
            $path = $image->storeAs($file_path, $name, 'upload');
            $request['image'] = $path;
        }
        $request['is_active'] = $request->is_active ? 1 : 0;
        $request['is_menu'] = $request->is_menu ? 1 : 0;
        $request['is_featured'] = $request->is_featured ? 1 : 0;
        $category->update($request->all());
        $seo = SeoController::update('category',$category);
        return redirect()->route('category.index')->with('success', 'Category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = $this->category->find($id);
        if(count($category->pages)) {
            return back()->withErrors('Sorry cannot remove category, this category is is use.');
        }
        $seo = SeoController::delete($category);
        $category->delete();
        return back()->with('success', 'Category deleted successfully');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Contact;
use App\Models\Comment;

class DashboardController extends Controller
{
   /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.dashboard');
    }


    public function allContact()
    {
        $contacts = Contact::get();
        return view('backend.contact.index', compact('contacts'));
    }

    public function getContact($id)
    {
        $contact = Contact::find($id);
        $contact->is_viewed = 1;
        $contact->save();
        return view('backend.contact.show', compact('contact'));
    }
    public function allComment()
    {
        $comments = Comment::get();
        return view('backend.comment.index', compact('comments'));
    }

    public function getComment($id)
    {
        $comment = Comment::find($id);
        $comment->is_active = 1;
        $comment->save();
        return view('backend.comment.show', compact('comment'));
    }
}

app/Http/Controllers/Backend/FaqController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Faq;

class FaqController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $faqs = Faq::all();
        return view('backend.faq.index', compact('faqs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.faq.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request , ['question' => 'required|unique:faqs', 'answer' => 'required']);
        Faq::create($request->all());
        return redirect()->route('faq.index')->with('success', 'FAQ created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $faq = Faq::find($id);
        return view('backend.faq.edit', compact('faq'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $faq = Faq::find($id);
        $this->validate($request, ['question' => 'required|unique:faqs,question,'.$faq->id, 'answer' => 'required']);

        $request['is_active'] = $request->is_active ? 1 : 0;
        $faq->update($request->all());
        return redirect()->route('faq.index')->with('success', 'FAQ updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $faq = Faq::find($id);
       $faq->delete();
       return redirect()->route('faq.index')->with('success', 'FAQ deleted successfully');
    }
}

app/Http/Controllers/Backend/GalleryController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Gallery;
use App\Http\Controllers\SeoController;
use Image;

class GalleryController extends Controller
{

     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(Gallery $gallery)
    {
        $this->middleware('auth');
        $this->gallery = $gallery;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $galleries = $this->gallery->latest()->get();
       return view('backend.gallery.index', compact('galleries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('backend.gallery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //return $request->all();
        $this->validate($request, ['title' => 'required|unique:galleries', 'file' => 'required|mimes:jpg,png,jpeg|max:2048']);
        $request['slug'] = str_slug($request->title);

        if ($request->has('file')) {
            $image = $request->file('file');
            $ext =  $image->getClientOriginalExtension();
            $file_path ='/gallery';
            $name = $request->slug.'.'.$ext;
            $path = $image->storeAs($file_path, $name, 'upload');
            $request['image'] = $path;
        }
        // Video from Youtube
        $request['link'] = $request->link ? $request->link : url('/');
        $gallery = $this->gallery->create($request->all());
        $seo = SeoController::create('gallery', $gallery);
        return redirect()->route('gallery.index')->with('success', 'Gallery created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $gallery = $this->gallery->find($id);
        return view('backend.gallery.edit', compact('gallery'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $gallery = $this->gallery->find($id);
        $this->validate($request, ['title' => 'required|unique:galleries,title,'.$gallery->id, 'file' => 'image|mimes:jpg,png,jpeg|max:2048']);
        $request['slug'] = str_slug($request->title);

        if ($request->has('file')) {

            $image = $request->file('file');
            $ext =  $image->getClientOriginalExtension();
            $file_path ='/gallery';
            $name = $request->slug.'.'.$ext;
            $path = $image->storeAs($file_path, $name, 'upload');
            $request['image'] = $path;
        }
        $request['is_active'] = $request->is_active ? 1 : 0;
        $request['is_slider'] = $request->is_slider ? 1 : 0;
        $request['is_featured'] = $request->is_featured ? 1 : 0;
        $request['link'] = $request->link ? $request->link : url('/');

        $gallery->update($request->all());
        $seo = SeoController::update('gallery', $gallery);
        return redirect()->route('gallery.index')->with('success', 'Gallery updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $gallery = $this->gallery->find($id);
        $gallery->delete();
        return back()->with('success', 'Gallery deleted successfully');
    }

    public function uploadFile(Request $request)
    {
       $this->validate($request, ['file'=>'mimes:jpeg,gif,png']); 

        if ($request->hasFile('file')) {

            $image = $request->file('file');
            $ext =  $image->getClientOriginalExtension();
            $file_name = $image->getClientOriginalName();
            $slug = str_slug($file_name);
            $file_path ='/gallery';
            $name = $slug.'.'.$ext;
            $path = $image->storeAs($file_path, $name, 'upload');
            $request['image'] = $path;
        }
        $request['title'] = $file_name;
        $request['slug'] = $slug;
        $request['is_active'] = 1;
        $gallery =  Gallery::create($request->all());
        return response()->json($gallery);
    }

    public function uploadUrl(Request $request)
    {
        $this->validate($request, ['image_url'=>'required|url']); 
       
        $path = $request->image_url;
        $filename = basename($path);
        if (file_exists(public_path() . '/uploads/gallery/'.$filename)) {
                 $filename = time().$filename;
        }
        $image_path = '/uploads/gallery/'.$filename;
        $img = Image::make($path)->save(public_path().$image_path);
        $img->resize(200,200)->save(public_path().$thumbnail_path);
        $data['title'] = $filename;
        $data['image'] =  $image_path;
        $request['is_active'] = 1;
        $gallery = Gallery::create($data);
        return response ()->json ( $gallery );
    }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    public function index(){
      return view('backend.orders.index');
    }
}

resources/views/backend/workers/_form.blade.php
<div class="row">
    <div class="col-md-6">
      <div class="form-group">
         <label>User <font color="red">*</font></label>
        {{Form::select('user_id', $users , isset($worker) ? $worker->user_id: null, ['class' => 'form-control'])}}
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
          <label>Status</label>
          {{ Form::select('status', [''=> 'Select Status', '1' => 'Active', '0' => 'Inactive'],null, ['id' => 'status', 'class' => 'form-control']) }}
      </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
      <div class="form-group">
         <label>Slug <font color="red">*</font></label>
         {{Form::text('slug', null, ['class' => 'form-control', 'required' => 'false', 'placeholder' => 'Slug..'])}}
      </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
           <label>Hour Rate <font color="red">*</font></label>
           {{Form::text('hour_rate', null, ['class' => 'form-control', 'required' => 'false', 'placeholder' => 'Hour rate..'])}}
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
      <div class="form-group">
         <label>Working Hour per Day <font color="red">*</font></label>
         {{Form::text('working_hour_per_day', null, ['class' => 'form-control', 'required' => 'false', 'placeholder' => 'Working Hour per Day..'])}}
      </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
           <label>Working Day per Month <font color="red">*</font></label>
           {{Form::text('working_day_per_month', null, ['class' => 'form-control', 'required' => 'false', 'placeholder' => 'Working Day per Month..'])}}
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label>Rate Type <font color="red">*</font></label>
            {{ Form::select('rate_type', [''=> 'Select Status', '0' => 'Hourly', '1' => 'Daily', '2'=>'Weekly', '3'=> 'Monthly'],null, ['id' => 'status', 'class' => 'form-control']) }}
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
      <div class="form-group">
         <label>Availability <font color="red">*</font></label>
         {{Form::text('availability', null, ['class' => 'form-control', 'required' => 'false', 'placeholder' => 'Availability..'])}}
      </div>
    </div>
</div>

resources/views/backend/workers/create.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
              {{-- @if(count($errors))
              <div class="alert alert-danger">
              <button type="button" aria-hidden="true" class="close">×</button>
              @foreach($errors as $error)
                <span>{{$error}}</span>
              @endforeach
          </div>
          @endif --}}
                <h4 class="title">Add New Worker</h4>
            </div>
            <div class="content">
                {{Form::open(['route' => ['worker.store'], 'method' => 'POST', 'enctype' => 'multipart/form-data'])}}
                    @include('backend.workers._form')
                    <button type="submit" class="btn btn-info btn-fill pull-right">Create</button>
                    <div class="clearfix"></div>
                {{Form::close()}}
            </div>
        </div>
    </div>

</div>

@stop

resources/views/backend/workers/edit.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
              {{-- @if(count($errors))
              <div class="alert alert-danger">
              <button type="button" aria-hidden="true" class="close">×</button>
              @foreach($errors as $error)
                <span>{{$error}}</span>
              @endforeach
          </div>
          @endif --}}
                <h4 class="title">Edit Job</h4>
            </div>
            <div class="content">
                {{Form::model($worker, ['route' => ['worker.update', $worker->id], 'method' => 'PATCH', 'enctype' => 'multipart/form-data'])}}
                    @include('backend.workers._form')
                    <button type="submit" class="btn btn-info btn-fill pull-right">Update</button>
                    <div class="clearfix"></div>
                {{Form::close()}}
            </div>
        </div>
    </div>

</div>

@stop

resources/views/backend/workers/index.blade.php
@extends('layouts.backend')
@section('content')
  <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header">

               {{--  @if ($message = Session::get('success'))
                  <div class="alert alert-success">
                <button type="button" aria-hidden="true" class="close">×</button>
                  <span>{{$message}}</span>
            </div>
          @endif --}}
                    <h4 class="title">Worker Table with action   
                  <a href="{{route('worker.create')}}" class="btn-success btn-sm btn pull-right"><i class="fa fa-plus"></i> Add New</a>
               </h4>
                    <p class="category">Here is a list for this all workers</p>
                   
                </div>
                <div class="content table-responsive">
                    <table class="table table-hover table-striped table-sm">
              <thead>
                  <tr>
                      <th class="text-center">#</th>
                      <td>User Id</td>
                      <td>Hour Rate</td>
                      <td>Working Hour per Day</td>
                      <td>Working Day per Month</td>
                      <td>Availability</td>
                      <td>Rate Type</td>
                      <td>Status</td>
                      <td>Slug</td>
                      <td>Action</td>
                  </tr>
              </thead>
              <tbody>
                @foreach($workers as $key => $worker)
                  <tr>
                      <td class="text-center">{{++$key}}</td>
                      <td>{{ $worker->user->email }}</td>
                      <td>{{ $worker->hour_rate }}</td>
                      <td>{{ $worker->working_hour_per_day}}</td>
                      <td>{{ $worker->working_day_per_month }}</td>
                      <td>{{ $worker->availability}}</td>
                      <td>{{ $worker->rate_type }}</td>
                      <td>{{ $worker->status }}</td>
                      <td>{{ $worker->slug }}</td>
                      <td class="td-actions">
                          <a href="{{route('worker.show', $worker->id)}}" rel="tooltip" title="View Category" class="btn btn-info btn-simple btn-xs">
                            <i class="fa fa-eye"></i>
                          </a>
                        
                            <a href="{{route('worker.edit', $worker->id)}}" rel="tooltip" title="Edit worker" class="btn btn-success btn-simple btn-xs">
                            <i class="fa fa-edit"></i>
                          </a>
             
                          <a data-toggle="modal" data-target="#deleteForm{{$worker->id}}" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs">
                              <i class="fa fa-times"></i>
                          </a>
                         
                  <!-- Modal -->
                  <div class="modal fade" id="deleteForm{{$worker->id}}" role="dialog">
                    <div class="modal-dialog">
                    <!-- Modal content-->
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                          <h3 class="modal-title">Delete</h3>
                        </div>
                        {{Form::open(['route' => ['worker.destroy', $worker->id],'method' => 'DELETE', 'id' => 'delete'] )}}
                        <div class="modal-body">
                          
                          <strong>Are you sure want to Delete this Worker?</strong>
                          
                        </div>
                        <div class="modal-footer">
                          <button class="btn btn-small btn-fulltime">Yes</button>
                          <button type="button" class="btn btn-small btn-danger" data-dismiss="modal">No</button>
                          
                        </div>
                        {{Form::close()}}
                      </div>
                    </div>
                  </div>
                      </td>
                  </tr>
                 @endforeach
              </tbody>
          </table>
                </div>
            </div>
        </div>
    </div>
@stop

@extends('layouts.backend')

@section('content')
  <div class="row">
    @if (Session::has('message'))
        <div class="alert alert-info">{{ Session::get('message') }}</div>
    @endif
    <div class="card w-100 m-2">
      <div class="card-header">
        <label>Worker index</label>
      </div>
      <div class="card-body">
        <div class="row">
            <a href="{{url('/workers/create')}}" class="btn btn-primary float-right">Create New</a>
                      
        </div>
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <td>ID</td>
                    <td>User Id</td>
                    <td>Hour Rate</td>
                    <td>Working Hour per Day</td>
                    <td>Working Day per Month</td>
                    <td>Availability</td>
                    <td>Rate Type</td>
                    <td>Status</td>
                    <td>Slug</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
            @foreach($workers as $key => $value)
                <tr>
                    <td>{{ $value->id }}</td>
                    <td>{{ $value->user->email }}</td>
                    <td>{{ $value->hour_rate }}</td>
                    <td>{{ $value->working_hour_per_day}}</td>
                    <td>{{ $value->working_day_per_month }}</td>
                    <td>{{ $value->availability}}</td>
                    <td>{{ $value->rate_type }}</td>
                    <td>{{ $value->status }}</td>
                    <td>{{ $value->slug }}</td>
                    <td>
                        <a class="btn btn-small btn-success" href="{{ URL::to('/workers/' . $value->id) }}">Show</a>
                        <a class="btn btn-small btn-info" href="{{ URL::to('/workers/' . $value->id . '/edit') }}">Edit</a>
                        <form method="POST" action="/workers/{{ $value->id }}" class="d-inline">
                            @csrf
                            @method('DELETE')
                            <input type="submit" class="btn btn-danger btn-small" value="Delete">
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {{ $workers->links() }}
      </div>
    </div>

  </div>

@endsection

resources/views/backend/workers/show.blade.php
@extends('layouts.backend')

@section('content')
  <div class="row">
    <div class="col-12">  
      <div class="form-group">
        <label for="user">user</label>
        <input name="user_id" value="{{ $worker->user_id }}" type="text" class="form-control" id="user" aria-describedby="userHelp" placeholder="Enter user">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">status</label>
        <select class="form-control" name="status" value="{{ $worker->status }}">
          <option>Default select</option>
          <option value="0">Active</option>
          <option value="1">Inactive</option>
        </select>
      </div>
      <div class="form-group">
        <label for="slug">Slug</label>
        <input name="slug" value="{{ $worker->slug }}" type="text" class="form-control" id="slug" aria-describedby="slugHelp" placeholder="Enter slug" >
      </div>
      <div class="form-group">
        <label for="parent">Hour Rate</label>
        <input name="hour_rate" value="{{ $worker->hour_rate }}" type="text" class="form-control" id="part" aria-describedby="parentHelp" placeholder="Enter hour rate">
      </div>
      <div class="form-group">
        <label for="parent">Working Hour per Day</label>
        <input name="working_hour_per_day" value="{{ $worker->working_hour_per_day }}" type="text" class="form-control" id="part" aria-describedby="parentHelp" placeholder="Enter hour per day">
      </div>
      <div class="form-group">
        <label for="parent">Working Day per Month</label>
        <input name="working_day_per_month" value="{{ $worker->working_day_per_month }}" type="text" class="form-control" id="part" aria-describedby="parentHelp" placeholder="Enter day per month">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Rate Type</label>
        <select class="form-control" name="rate_type" value="{{ $worker->rate_type }}">
          <option>Default select</option>
          <option value="0">Hourly</option>
          <option value="1">Daily</option>
          <option value="1">Weekly</option>
          <option value="1">Monthly</option>
        </select>
      </div>
      <div class="form-group">
        <label for="parent">Availability</label>
        <input name="availability" type="text" class="form-control" id="part" aria-describedby="parentHelp" placeholder="Availability" value="{{ $worker->availability }}" >
      </div>
    </div>
  </div>
@endsection