routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');
Route::post('comment', 'HomeController@storeComment')->name('comment');
Route::post('contacts', 'HomeController@storeContact')->name('contact');
Route::post('newsletter', 'HomeController@storeNewsLetter')->name('newsletter');
Route::get('sitemap', 'HomeController@sitemap')->name('sitemap');
Route::get('sitemap.xml', 'HomeController@sitemap')->name('sitemap');

Auth::routes();
Route::get('/backup', 'HomeController@backup')->middleware('auth'); 
Route::get('/refresh', 'HomeController@refresh')->middleware('auth');
Route::group(['middleware' => ['auth', 'permission'], 'prefix' => 'backend', 'namespace' => 'Backend'], function() {

	Route::get('/', 'DashboardController@index')->name('backend.dashboard');
	Route::resource('category', 'CategoryController');
	Route::resource('page', 'PageController');
	Route::resource('post', 'PostController');
	Route::resource('gallery', 'GalleryController');
	Route::resource('user', 'UserController');
	Route::resource('role', 'RoleController');
	Route::resource('faq', 'FaqController');
	Route::resource('partner', 'PartnerController');
	Route::resource('testimonial', 'TestimonialController');
  Route::resource('job', 'JobController');
  Route::resource('worker', 'WorkerController');
  Route::resource('order', 'OrderController');
	Route::get('contact', 'DashboardController@allContact')->name('contact.index');
	Route::get('contact/{id}', 'DashboardController@getContact')->name('contact.show');
	Route::get('comment', 'DashboardController@allComment')->name('comment.index');
	Route::get('comment/{id}', 'DashboardController@getComment')->name('comment.show');
	Route::get('setting', 'SettingController@index')->name('setting.index');
	Route::post('setting', 'SettingController@store')->name('setting.store');
});
/*Front Route*/
Route::get('/{slug}', 'RouteController@index')->name('url');

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Http\Controllers\SeoController;

class CategoryController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(Category $category)
    {
        $this->middleware('auth');
        $this->category = $category;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->category->latest()->get();
        return view('backend.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('backend.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, ['title' => 'required|unique:seos', 'file' => 'image|mimes:jpg,png,jpeg,gif|max:2048','description' => 'max:240']);

        $request['slug'] = str_slug($request->title);

        if ($request->has('file')) {

            $image = $request->file('file');
            $ext =  $image->getClientOriginalExtension();
            $file_path ='/categories';
            $name = $request->slug.'.'.$ext;
            $path = $image->storeAs($file_path, $name, 'upload');
            $request['image'] = $path;
        }

        $category = $this->category->create($request->all());
        $seo = SeoController::create('category', $category);

        return redirect()->route('category.index')->with('success', 'Category created successfully');
        

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
       return redirect($category->slug);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->category->find($id);
        return view('backend.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = $this->category->find($id);
        $this->validate($request, ['title' => 'required|unique:categories,title,'.$category->id, 'file' => 'image|mimes:jpg,png,jpeg,gif|max:2048','description' => 'max:240']);

        $request['slug'] = str_slug($request->title);
        if ($request->has('file')) {
            $image = $request->file('file');
            $ext =  $image->getClientOriginalExtension();
            $file_path ='/categories';
            $name = $request->slug.'.'.$ext;
            $path = $image->storeAs($file_path, $name, 'upload');
            $request['image'] = $path;
        }
        $request['is_active'] = $request->is_active ? 1 : 0;
        $request['is_menu'] = $request->is_menu ? 1 : 0;
        $request['is_featured'] = $request->is_featured ? 1 : 0;
        $category->update($request->all());
        $seo = SeoController::update('category',$category);
        return redirect()->route('category.index')->with('success', 'Category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = $this->category->find($id);
        if(count($category->pages)) {
            return back()->withErrors('Sorry cannot remove category, this category is is use.');
        }
        $seo = SeoController::delete($category);
        $category->delete();
        return back()->with('success', 'Category deleted successfully');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Contact;
use App\Models\Comment;

class DashboardController extends Controller
{
   /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.dashboard');
    }


    public function allContact()
    {
        $contacts = Contact::get();
        return view('backend.contact.index', compact('contacts'));
    }

    public function getContact($id)
    {
        $contact = Contact::find($id);
        $contact->is_viewed = 1;
        $contact->save();
        return view('backend.contact.show', compact('contact'));
    }
    public function allComment()
    {
        $comments = Comment::get();
        return view('backend.comment.index', compact('comments'));
    }

    public function getComment($id)
    {
        $comment = Comment::find($id);
        $comment->is_active = 1;
        $comment->save();
        return view('backend.comment.show', compact('comment'));
    }
}

app/Http/Controllers/Backend/FaqController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Faq;

class FaqController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $faqs = Faq::all();
        return view('backend.faq.index', compact('faqs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.faq.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request , ['question' => 'required|unique:faqs', 'answer' => 'required']);
        Faq::create($request->all());
        return redirect()->route('faq.index')->with('success', 'FAQ created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $faq = Faq::find($id);
        return view('backend.faq.edit', compact('faq'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $faq = Faq::find($id);
        $this->validate($request, ['question' => 'required|unique:faqs,question,'.$faq->id, 'answer' => 'required']);

        $request['is_active'] = $request->is_active ? 1 : 0;
        $faq->update($request->all());
        return redirect()->route('faq.index')->with('success', 'FAQ updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $faq = Faq::find($id);
       $faq->delete();
       return redirect()->route('faq.index')->with('success', 'FAQ deleted successfully');
    }
}

app/Http/Controllers/Backend/GalleryController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Gallery;
use App\Http\Controllers\SeoController;
use Image;

class GalleryController extends Controller
{

     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(Gallery $gallery)
    {
        $this->middleware('auth');
        $this->gallery = $gallery;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $galleries = $this->gallery->latest()->get();
       return view('backend.gallery.index', compact('galleries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('backend.gallery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //return $request->all();
        $this->validate($request, ['title' => 'required|unique:galleries', 'file' => 'required|mimes:jpg,png,jpeg|max:2048']);
        $request['slug'] = str_slug($request->title);

        if ($request->has('file')) {
            $image = $request->file('file');
            $ext =  $image->getClientOriginalExtension();
            $file_path ='/gallery';
            $name = $request->slug.'.'.$ext;
            $path = $image->storeAs($file_path, $name, 'upload');
            $request['image'] = $path;
        }
        // Video from Youtube
        $request['link'] = $request->link ? $request->link : url('/');
        $gallery = $this->gallery->create($request->all());
        $seo = SeoController::create('gallery', $gallery);
        return redirect()->route('gallery.index')->with('success', 'Gallery created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $gallery = $this->gallery->find($id);
        return view('backend.gallery.edit', compact('gallery'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $gallery = $this->gallery->find($id);
        $this->validate($request, ['title' => 'required|unique:galleries,title,'.$gallery->id, 'file' => 'image|mimes:jpg,png,jpeg|max:2048']);
        $request['slug'] = str_slug($request->title);

        if ($request->has('file')) {

            $image = $request->file('file');
            $ext =  $image->getClientOriginalExtension();
            $file_path ='/gallery';
            $name = $request->slug.'.'.$ext;
            $path = $image->storeAs($file_path, $name, 'upload');
            $request['image'] = $path;
        }
        $request['is_active'] = $request->is_active ? 1 : 0;
        $request['is_slider'] = $request->is_slider ? 1 : 0;
        $request['is_featured'] = $request->is_featured ? 1 : 0;
        $request['link'] = $request->link ? $request->link : url('/');

        $gallery->update($request->all());
        $seo = SeoController::update('gallery', $gallery);
        return redirect()->route('gallery.index')->with('success', 'Gallery updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $gallery = $this->gallery->find($id);
        $gallery->delete();
        return back()->with('success', 'Gallery deleted successfully');
    }

    public function uploadFile(Request $request)
    {
       $this->validate($request, ['file'=>'mimes:jpeg,gif,png']); 

        if ($request->hasFile('file')) {

            $image = $request->file('file');
            $ext =  $image->getClientOriginalExtension();
            $file_name = $image->getClientOriginalName();
            $slug = str_slug($file_name);
            $file_path ='/gallery';
            $name = $slug.'.'.$ext;
            $path = $image->storeAs($file_path, $name, 'upload');
            $request['image'] = $path;
        }
        $request['title'] = $file_name;
        $request['slug'] = $slug;
        $request['is_active'] = 1;
        $gallery =  Gallery::create($request->all());
        return response()->json($gallery);
    }

    public function uploadUrl(Request $request)
    {
        $this->validate($request, ['image_url'=>'required|url']); 
       
        $path = $request->image_url;
        $filename = basename($path);
        if (file_exists(public_path() . '/uploads/gallery/'.$filename)) {
                 $filename = time().$filename;
        }
        $image_path = '/uploads/gallery/'.$filename;
        $img = Image::make($path)->save(public_path().$image_path);
        $img->resize(200,200)->save(public_path().$thumbnail_path);
        $data['title'] = $filename;
        $data['image'] =  $image_path;
        $request['is_active'] = 1;
        $gallery = Gallery::create($data);
        return response ()->json ( $gallery );
    }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    public function index(){
      return view('backend.orders.index');
    }
}

resources/views/backend/page/_form.blade.php
<div class="row">
    <div class="col-md-12">
  		<div class="form-group">
  			 <label>Page Title <font color="red">*</font></label>
  			 {{Form::text('title', null, ['class' => 'form-control', 'required' => 'true', 'placeholder' => 'Page Title..'])}}
  		</div>
  	</div>
</div>
<div class="row">
  	<div class="col-md-6">
  		<div class="form-group">
  			  <label>Keyword <small style="text-transform: lowercase;">(with commas .. eg('Agency in Nepal, we sell your product,)</small> </label>
  			 {{Form::text('keyword', null, ['class' => 'form-control', 'placeholder' => 'Keywords with commas'])}}
  		</div>
  	</div>

    <div class="col-md-3">
        <div class="form-group">
            <label>Category</label>
            {{Form::select('category_id', $categories, null, ['class' => 'form-control'])}}
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <label>Type</label>
            {{Form::select('type', pageType(), null, ['class' => 'form-control'])}}
        </div>
    </div>
</div>
<div class="row">
  	<div class="col-md-12">
  		<div class="form-group">
  			 <label>Description <small style="text-transform: lowercase;">(max : 240 words, this is a meta description for seo)</small> </label>
  			 {{Form::textarea('description', null, ['class' => 'form-control', 'maxlength' => 240, 'size' => '3x5', 'placeholder' => 'Meta Description for SEO'])}}
  		</div>
  	</div>
</div>
<div class="row">
  	<div class="col-md-12">
  		<div class="form-group">
  			 <label>Content </label>
  			 {{Form::textarea('content', null, ['class' => 'form-control editor', 'size' => '3x5', 'placeholder' => 'Page Content'])}}
  		</div>
  	</div>
 </div>
 <div class="row">
  	<div class="col-md-3">
  		<div class="form-group">
  			 <label>Image </label>
  			 {{Form::file('file')}}
  		</div>

      @if(isset($page->image))
          <img class="img-responsive img-rounded" src="{{$page->image}}" alt="{{$page->slug}}" height="60" width="80">
      @endif
  	</div>
    <div class="col-md-3">
      <div class="form-group">
         <label>Video Url <small style="text-transform: lowercase;">(Video Url : (embed code url only))</small></label>
         {{Form::text('video', null, ['class' => 'form-control', 'placeholder' => 'Youtube Video Url'])}}
      </div>

      @if(isset($page->video))
          <iframe width="100" height="100" src="{{$page->video}}"></iframe> 
      @endif
    </div>
  	<div class="col-md-2">
  		<div class="form-group">
  			 <label for="active">Active </label>
  			 {{Form::checkbox('is_active', 1, isset($page) ? ($page->is_active ? true : false) : true, ['id' => 'active'])}}
  		</div>
  	</div>
  	<div class="col-md-2">
  		<div class="form-group">
  			 <label for="menu">Menu </label>
  			 {{Form::checkbox('is_menu', 1, isset($page) ? ($page->is_menu ? true : false) : false, ['id' => 'menu'])}}
  		</div>
  	</div>
  	<div class="col-md-2">
  		<div class="form-group">
  			 <label for="featured">Featured </label>
  			 {{Form::checkbox('is_featured', 1, isset($page) ? ($page->is_featured ? true : false) : false, ['id' => 'featured'])}}
  		</div>
  	</div>
</div>

resources/views/backend/page/create.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">Add New page</h4>
            </div>
            <div class="content">
                {{Form::open(['route' => ['page.store'], 'method' => 'POST', 'enctype' => 'multipart/form-data'])}}
                    @include('backend.page._form')
                    <button type="submit" class="btn btn-info btn-fill pull-right">Create</button>
                    <div class="clearfix"></div>
               	{{Form::close()}}
            </div>
        </div>
    </div>

</div>

@stop

resources/views/backend/page/edit.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
            	{{-- @if(count($errors))
            	<div class="alert alert-danger">
			        <button type="button" aria-hidden="true" class="close">×</button>
			        @foreach($errors as $error)
			        	<span>{{$error}}</span>
			        @endforeach
		    	</div>
		    	@endif --}}
                <h4 class="title">Edit Page</h4>
            </div>
            <div class="content">
                {{Form::model($page, ['route' => ['page.update', $page->id], 'method' => 'PATCH', 'enctype' => 'multipart/form-data'])}}
                    @include('backend.page._form')
                    <button type="submit" class="btn btn-info btn-fill pull-right">Update</button>
                    <div class="clearfix"></div>
               	{{Form::close()}}
            </div>
        </div>
    </div>

</div>

@stop

resources/views/backend/page/index.blade.php
@extends('layouts.backend')
@section('content')
	<div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header">

                  	<h4 class="title">Manage Page Table with Action  <a href="{{route('page.create')}}" class="btn-success btn-sm btn pull-right"><i class="fa fa-plus"></i> Add New</a></h4>
                    <p class="page">Here is a list for this all Page.</p>
                   
                </div>
                <div class="content table-responsive">
                    <table class="table table-hover table-striped">
					    <thead>
					        <tr>
					            <th class="text-center">#</th>
					            <th>Title</th>
					            <th>Description</th>
					            <th>Type</th>
					            <th>Image</th>
					            <th>Status</th>
					            <th>Actions</th>
					        </tr>
					    </thead>
					    <tbody>
					    	@foreach($pages as $key => $page)
					        <tr>
					            <td class="text-center">{{++$key}}</td>
					            <td>{{$page->title}}</td>
					            <td>{{$page->description}}</th>
					            <td>{{$page->type}}</td>
					            <th><img src="{{$page->image}}"></th>
					            <td>{{$page->is_active ? 'Active' : 'Deactive'}}</td>
					            <td class="td-actions">
					                <a href="{{route('page.show', $page->id)}}" rel="tooltip" title="View Page" class="btn btn-info btn-simple btn-xs">
					                    <i class="fa fa-eye"></i>
					                </a>
					                <a href="{{route('page.edit', $page->id)}}" rel="tooltip" title="Edit Page" class="btn btn-success btn-simple btn-xs">
					                    <i class="fa fa-edit"></i>
					                </a>
					                <a data-toggle="modal" data-target="#deleteForm{{$page->id}}" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs">
					                    <i class="fa fa-times"></i>
					                </a>
									<!-- Modal -->
									<div class="modal fade" id="deleteForm{{$page->id}}" role="dialog">
										<div class="modal-dialog">
										<!-- Modal content-->
											<div class="modal-content">
												<div class="modal-header">
													<button type="button" class="close" data-dismiss="modal">&times;</button>
													<h3 class="modal-title">Delete</h3>
												</div>
												{{Form::open(['route' => ['page.destroy', $page->id],'method' => 'DELETE', 'id' => 'delete'] )}}
												<div class="modal-body">
													
													<strong>Are you sure want to Delete this Page "{{$page->title}}"?</strong>
													
												</div>
												<div class="modal-footer">
													<button class="btn btn-small btn-fulltime">Yes</button>
													<button type="button" class="btn btn-small btn-danger" data-dismiss="modal">No</button>
													
												</div>
												{{Form::close()}}
											</div>
										</div>
									</div>
					            </td>
					        </tr>
					       @endforeach
					    </tbody>
					</table>
                </div>
            </div>
        </div>
    </div>
@stop